baseURL = ""
languageCode = "en-us"
title = "Brian H Grant's Blog"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Reliable Brian"
author = "Brian H Grant"
#copyright = "2020-2021"
description = "Reflections on the world of Site Reliability Engineering \n and my journey in technology"
profilePicture = "/images/1a79f3cd_o.gif"
keywords = ["sre"]
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/brianhgrant"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/brianhgrant"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:bhgrant8@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  weight = 400
  identifier = "contact"
  url = "/contact/"
